name: Daily Insta Post
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install instagrapi requests
      - name: Run Script
        env:
          INSTA_USER: ${{ secrets.INSTA_USER }}
          INSTA_PASS: ${{ secrets.INSTA_PASS }}
        run: python main.py
